#!/bin/bash

    sudo apt-get install -y net-tools
    sudo apt install -y nmap 
    sudo apt install -y zenity 
    sudo apt install -y tcpdump
    sudo apt install -y git
    sudo apt install -y ssmtp
    
chmod +x *

echo "Escribe tu Direccion de GMAIL donde quieres que te lleguen las alertas"
read mensaje
echo "$mensaje" > correo

./configuracion-ssmtp
./deteccionDeInfracciones

rm instalador

sudo reboot now

