#!/bin/bash

if [[ $# -eq 0 ]]; then
    zenity --error --text "Tienes que poner la IP del host"
    exit 0
fi

ping_output=$(ping -c 1 $1)

if [[ $ping_output =~ "bytes from" ]]; then
    if [[ $ping_output =~ "ttl="([0-9]+) ]]; then
        ttl=${BASH_REMATCH[1]}
        if [[ $ttl -gt 64 ]]; then
        zenity --info --text "El equipo $1 es un equipo Windows."
        else
            zenity --info --text "El equipo $1 es un equipo Linux."
        fi
    else
        clear
        zenity --info --text "No se pudo determinar el sistema operativo del equipo $1"
    fi
else
    clear
    zenity --info --text "No se pudo determinar el sistema operativo del equipo $1"
fi